<a href="https://colab.research.google.com/github/dusouza01/Analise-Risco-Credito/blob/main/credit_risk_kaagle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install -q kagglehub

import os
from google.colab import userdata
import kagglehub

os.environ["KAGGLE_API_TOKEN"] = userdata.get("KAGGLE_API_TOKEN")

In [ ]:
import kagglehub

caminho = kagglehub.dataset_download(
    "laotse/credit-risk-dataset"
)

print("Dataset baixado em:", caminho)

Using Colab cache for faster access to the 'credit-risk-dataset' dataset.
Dataset baixado em: /kaggle/input/credit-risk-dataset

In [ ]:
import os

for pasta, subpastas, arquivos in os.walk(caminho):
    for arquivo in arquivos:
        print(os.path.join(pasta, arquivo))

/kaggle/input/credit-risk-dataset/credit_risk_dataset.csv

In [ ]:
import pandas as pd
from pathlib import Path

arquivos_csv = list(Path(caminho).rglob("*.csv"))

print("CSVs encontrados:", arquivos_csv)

df_loan = pd.read_csv(caminho + "/credit_risk_dataset.csv")

CSVs encontrados: [PosixPath('/kaggle/input/credit-risk-dataset/credit_risk_dataset.csv')]

Descrição de Variáveis

person_age: Idade da pessoa que está solicitando o empréstimo.

person_income: Renda anual da pessoa.

person_home_ownership: Tipo de propriedade ou condição de moradia da pessoa.
- rent: A pessoa mora em um imóvel alugado.
- mortgage: A pessoa possui um imóvel financiado, com uma hipoteca ou dívida associada.
- own: A pessoa possui imóvel próprio, totalmente quitado.
- other: Outras categorias de moradia que podem ser específicas do conjunto de dados.

person_emp_length: Tempo de experiência profissional da pessoa, em anos.

loan_intent: Finalidade do empréstimo solicitado.

loan_grade: Classificação atribuída ao empréstimo com base no risco de crédito do solicitante.
- A: A pessoa apresenta excelente perfil de crédito, indicando baixo risco.
- B: A pessoa apresenta risco relativamente baixo, mas possui um perfil de crédito inferior ao da categoria A.
- C: A pessoa apresenta um perfil de crédito moderado.
- D: A pessoa apresenta um risco maior em comparação com as categorias anteriores.
- E: A pessoa apresenta um perfil de crédito mais fraco, indicando maior risco.
- F: A pessoa apresenta um risco de crédito significativo.
- G: A pessoa apresenta o pior perfil de crédito entre as categorias, indicando o maior risco.

loan_amnt: Valor do empréstimo solicitado pela pessoa.

loan_int_rate: Taxa de juros associada ao empréstimo.

loan_status: Situação do empréstimo, em que 0 indica ausência de inadimplência e 1 indica inadimplência.
- 0 — Não inadimplente: A pessoa pagou o empréstimo conforme os termos acordados, sem entrar em inadimplência.
- 1 — Inadimplente: A pessoa não cumpriu as condições de pagamento acordadas e entrou em inadimplência.

loan_percent_income: Percentual da renda anual da pessoa que é representado pelo valor do empréstimo.

cb_person_default_on_file: Histórico de inadimplência da pessoa, conforme os registros dos órgãos de proteção ao crédito.
- Y (Yes): A pessoa possui histórico de inadimplência registrado em seu histórico de crédito.
- N (No): A pessoa não possui histórico de inadimplência registrado.

cb_preson_cred_hist_length: Tempo de histórico de crédito da pessoa, em anos.

In [ ]:
df_loan.head(7)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
5,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2
6,26,77100,RENT,8.0,EDUCATION,B,35000,12.42,1,0.45,N,3

In [ ]:
df_loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

In [ ]:
df_loan[df_loan['person_emp_length'] >= df_loan['person_age']]

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
210,21,192000,MORTGAGE,123.0,VENTURE,A,20000,6.54,0,0.10,N,4

In [ ]:
df_loan.loc[df_loan['person_emp_length'] >= df_loan['person_age']]

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
210,21,192000,MORTGAGE,123.0,VENTURE,A,20000,6.54,0,0.10,N,4

In [ ]:
df_loan.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [ ]:
df_loan.loc[df_loan['person_emp_length'] >= df_loan['person_age']]

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
210,21,192000,MORTGAGE,123.0,VENTURE,A,20000,6.54,0,0.10,N,4